version: '3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    ports:
      - "9200:9200"
      - "9300:9300"
    
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.name=contextElasticSearch
    ports: 
      - "9300:9300"
      - "9200:9200" 
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1

    volume:
      - esundata:/usr/share/elasticsearch/data

  # logstash:
  #   image: docker.elastic.co/logstash/logstash:7.6.0
  #   ports:
  #     - "5000:5000"
  #     - "9600:9600"
  #   configs:
  #     - source: logstash_config
  #       target: /usr/share/logstash/config/logstash.yml
  #     - source: logstash_pipeline
  #       target: /usr/share/logstash/pipeline/logstash.conf
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx256m -Xms256m"
  #   networks:
  #     - elk
  #   deploy:
  #     mode: replicated
  #     replicas: 1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    Environment: 
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
        - '5601:5601'

    
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
volumes:
  esundata:

networks:
  elk:
    driver: overlay
